# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SensorLog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SensorBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SensorBatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSensorBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SensorBatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SensorBatch
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SensorBatch
    def Messages(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from SensorLog.SensorMessage import SensorMessage
            obj = SensorMessage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SensorBatch
    def MessagesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SensorBatch
    def MessagesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def SensorBatchStart(builder):
    builder.StartObject(2)

def Start(builder):
    SensorBatchStart(builder)

def SensorBatchAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(0, timestamp, 0)

def AddTimestamp(builder, timestamp):
    SensorBatchAddTimestamp(builder, timestamp)

def SensorBatchAddMessages(builder, messages):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(messages), 0)

def AddMessages(builder, messages):
    SensorBatchAddMessages(builder, messages)

def SensorBatchStartMessagesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMessagesVector(builder, numElems):
    return SensorBatchStartMessagesVector(builder, numElems)

def SensorBatchEnd(builder):
    return builder.EndObject()

def End(builder):
    return SensorBatchEnd(builder)
