# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SensorLog

class SensorType(object):
    BME688 = 0
    ENS160 = 1
    LSM6D032 = 2
    MPLAltimeter = 3
    BNO055 = 4
