# automatically generated by the FlatBuffers compiler, do not modify

# namespace: SensorLog

class SensorDataUnion(object):
    NONE = 0
    BME688Data = 1
    ENS160Data = 2
    LSM6D032Data = 3
    MPLAltimeterData = 4
    BNO055Data = 5
